"use client";

export function CitationsPanel(props: {
  show: boolean;
  messagesLength: number;
  backendLabel: string;
}) {
  const { show, messagesLength, backendLabel } = props;
  if (!show) return null;
  return (
    <div className="w-80 bg-card p-4 overflow-y-auto border-l border-border">
      <h3 className="font-semibold text-sm mb-3">Sources & Citations</h3>
      <div className="space-y-3">
        <div className="p-3 rounded-lg bg-muted/50 border">
          <div className="font-medium text-sm mb-1">
            Knowledge Base Document
          </div>
          <div className="text-xs text-muted-foreground mb-2">
            Last updated: {new Date().toLocaleDateString()}
          </div>
          <div className="text-sm">
            This information was retrieved from your uploaded documents and
            knowledge base.
          </div>
        </div>
        <div className="p-3 rounded-lg bg-muted/50 border">
          <div className="font-medium text-sm mb-1">AI Model Response</div>
          <div className="text-xs text-muted-foreground mb-2">
            Generated by: {backendLabel}
          </div>
          <div className="text-sm">
            Response generated based on conversation context and available
            knowledge.
          </div>
        </div>
        {messagesLength === 0 && (
          <div className="text-center text-muted-foreground text-sm p-4">
            Sources will appear here when you start chatting
          </div>
        )}
      </div>
    </div>
  );
}
